export const GET_BACKTESTS_REQUEST = "GET_BACKTESTS_REQUEST";
export const GET_BACKTESTS_SUCCESS = "GET_BACKTESTS_SUCCESS";
export const GET_BACKTESTS_FAIL = "GET_BACKTESTS_FAIL";

export const GET_BACKTEST_DETAILS_REQUEST = "GET_BACKTEST_DETAILS_REQUEST";
export const GET_BACKTEST_DETAILS_SUCCESS = "GET_BACKTEST_DETAILS_SUCCESS";
export const GET_BACKTEST_DETAILS_FAIL = "GET_BACKTEST_DETAILS_FAIL";
export const GET_BACKTEST_DETAILS_RESET = "GET_BACKTEST_DETAILS_RESET";