export const GET_TRADES_REQUEST = "GET_TRADES_REQUEST";
export const GET_TRADES_SUCCESS = "GET_TRADES_SUCCESS";
export const GET_TRADES_FAIL = "GET_TRADES_FAIL";

export const GET_TRADE_DETAILS_REQUEST = "GET_TRADE_DETAILS_REQUEST";
export const GET_TRADE_DETAILS_SUCCESS = "GET_TRADE_DETAILS_SUCCESS";
export const GET_TRADE_DETAILS_FAIL = "GET_TRADE_DETAILS_FAIL";
export const GET_TRADE_DETAILS_RESET = "GET_TRADE_DETAILS_RESET";